name: 201_RCAN_x1_LicensePlate
model_type: SRModel
scale: 1
num_gpu: 2
manual_seed: 10
datasets:
  train:
    name: LicensePlate_Train
    type: PairedImageDataset
    dataroot_gt: /kaggle/working/data/train_HR.lmdb
    dataroot_lq: F:/license_plate_dataset/license_plate_sr/lmdb/train_LR.lmdb
    io_backend:
      type: lmdb
    gt_size: 48
    use_hflip: false
    use_rot: false
    num_worker_per_gpu: 2
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true
  val:
    name: LicensePlate_Val
    type: PairedImageDataset
    dataroot_gt: /kaggle/working/data/val_HR.lmdb
    dataroot_lq: F:/license_plate_dataset/license_plate_sr/lmdb/val_LR.lmdb
    io_backend:
      type: lmdb
network_g:
  type: RCAN
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_group: 10
  num_block: 20
  squeeze_factor: 16
  upscale: 1
  res_scale: 1
  img_range: 255.0
  rgb_mean:
  - 0.4488
  - 0.4371
  - 0.404
path:
  pretrain_network_g: null
  strict_load_g: true
  resume_state: null
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: 0.0001
    weight_decay: 0
    betas:
    - 0.9
    - 0.99
  scheduler:
    type: MultiStepLR
    milestones:
    - 10000
    - 16000
    gamma: 0.5
  total_iter: 19100
  warmup_iter: -1
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean
val:
  val_freq: 100000000.0
  save_img: false
  pbar: true
  metrics:
    psnr:
      type: calculate_psnr_pt
      crop_border: 2
      test_y_channel: true
      better: higher
    ssim:
      type: calculate_ssim_pt
      crop_border: 2
      test_y_channel: true
      better: higher
logger:
  print_freq: 100
  save_checkpoint_freq: 1910.0
  use_tb_logger: true
  wandb:
    project: license_plate_sr
    entity: anhlone3
    resume_id: null
dist_params:
  backend: nccl
  port: 29500
