# Modified SRResNet w/o BN from:
# Photo-Realistic Single Image Super-Resolution Using a Generative Adversarial Network
# Use perceptual loss before ReLU as ESRGAN does

# general settings
name: 004_MSRGAN_x4_LicensePlate
model_type: SRGANModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: LicensePlate_Train
    type: PairedImageDataset
    dataroot_gt: /content/drive/MyDrive/license_plate_dataset/license_plate_sr/lmdb/train_HR.lmdb
    dataroot_lq: /content/drive/MyDrive/license_plate_dataset/license_plate_sr/lmdb/train_LR_x4.lmdb
    io_backend:
      type: lmdb

    gt_size: 48
    use_hflip: false
    use_rot: false

    # data loader (tối ưu Colab A100 GPU)
    num_worker_per_gpu: 16  # Tối đa hóa nạp batch cho Colab
    batch_size_per_gpu: 64  # GAN + VGG Perceptual Loss tốn thêm VRAM
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: LicensePlate_Val
    type: PairedImageDataset
    dataroot_gt: /content/drive/MyDrive/license_plate_dataset/license_plate_sr/lmdb/val_HR.lmdb
    dataroot_lq: /content/drive/MyDrive/license_plate_dataset/license_plate_sr/lmdb/val_LR_x4.lmdb
    io_backend:
      type: lmdb

# network structures
network_g:
  type: MSRResNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 16
  upscale: 4

network_d:
  type: VGGStyleDiscriminator
  num_in_ch: 3
  num_feat: 64

# path
path:
  pretrain_network_g: experiments/001_MSRResNet_x4_LicensePlate/models/net_g_latest.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [20000, 32000]
    gamma: 0.5

  total_iter: 38000  # 100 epochs (24,468 images / batch 64 * 100 epochs ~ 38,200 iters)
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1e-2
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-3

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 3800  # 10 epochs (382 iters/epoch * 10)
  save_img: false
  pbar: true

  metrics:
    psnr:
      type: calculate_psnr_pt
      crop_border: 4
      test_y_channel: true
      better: higher
    ssim:
      type: calculate_ssim_pt
      crop_border: 4
      test_y_channel: true
      better: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 3800
  use_tb_logger: true
  wandb:
    project: license_plate_sr
    entity: anhlone3
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

# command
# python basicsr/train.py -opt options/train/SRResNet_SRGAN/train_MSRGAN_x4.yml
